use std::fmt;

/// Tables that may be used with the typed LIVE and changefeed helpers.
///
/// Keeping this closed prevents a caller-controlled identifier from being
/// interpolated into `LIVE SELECT` or `SHOW CHANGES` statements.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum PlatformTable {
    Enterprise,
    Tenant,
    Principal,
    Group,
    OauthClient,
    McpServer,
    Profile,
    PolicyRevision,
    GatewayControlRevision,
    GatewayControlObject,
    GatewayControlActive,
    GatewayResourceSubscription,
    GatewayJwtRevocation,
    GatewayReplayId,
    GatewayAuthorizationRequest,
    GatewayAuthorizationCode,
    GatewayRefreshFamily,
    GatewayRefreshToken,
    Task,
    TaskIdempotency,
    TaskInput,
    ProviderJob,
    ProviderEvent,
    ArtifactBlob,
    ArtifactOccurrence,
    ArtifactGrant,
    ShareLink,
    ArtifactWriteCapability,
    ArtifactWriteRedemption,
    ArtifactAccessRequest,
    MediaTaskContext,
    MediaUsage,
    DomainUsage,
    Frame,
    CoordinateOperation,
    MapSource,
    MapDatasetRelease,
    MapActiveRelease,
    MapMobilityProfile,
    MapRestriction,
    MapOperationalSnapshot,
    MapRoute,
    MapRouteDependency,
    MapRouteMatrix,
    MapAcquisition,
    TimeSource,
    TimeAuthorityRelease,
    TimeActiveAuthority,
    TimeAcquisition,
    TimeCalendarVersion,
    TimeMissionEpoch,
    TimeTemporalEvent,
    TimeClockPolicy,
    RecordingDataset,
    Recording,
    RecordingLayer,
    RecordingReadGrant,
    RecordingProjectionReceipt,
    RecordingIngestStream,
    RecordingIngestBatch,
    RecordingBlueprint,
    Agent,
    Wake,
    AgentEpisode,
    AgentTask,
    AgentInputRequest,
    AuditEvent,
    OutboxEvent,
}

impl PlatformTable {
    pub const ALL: [Self; 68] = [
        Self::Enterprise,
        Self::Tenant,
        Self::Principal,
        Self::Group,
        Self::OauthClient,
        Self::McpServer,
        Self::Profile,
        Self::PolicyRevision,
        Self::GatewayControlRevision,
        Self::GatewayControlObject,
        Self::GatewayControlActive,
        Self::GatewayResourceSubscription,
        Self::GatewayJwtRevocation,
        Self::GatewayReplayId,
        Self::GatewayAuthorizationRequest,
        Self::GatewayAuthorizationCode,
        Self::GatewayRefreshFamily,
        Self::GatewayRefreshToken,
        Self::Task,
        Self::TaskIdempotency,
        Self::TaskInput,
        Self::ProviderJob,
        Self::ProviderEvent,
        Self::ArtifactBlob,
        Self::ArtifactOccurrence,
        Self::ArtifactGrant,
        Self::ShareLink,
        Self::ArtifactWriteCapability,
        Self::ArtifactWriteRedemption,
        Self::ArtifactAccessRequest,
        Self::MediaTaskContext,
        Self::MediaUsage,
        Self::DomainUsage,
        Self::Frame,
        Self::CoordinateOperation,
        Self::MapSource,
        Self::MapDatasetRelease,
        Self::MapActiveRelease,
        Self::MapMobilityProfile,
        Self::MapRestriction,
        Self::MapOperationalSnapshot,
        Self::MapRoute,
        Self::MapRouteDependency,
        Self::MapRouteMatrix,
        Self::MapAcquisition,
        Self::TimeSource,
        Self::TimeAuthorityRelease,
        Self::TimeActiveAuthority,
        Self::TimeAcquisition,
        Self::TimeCalendarVersion,
        Self::TimeMissionEpoch,
        Self::TimeTemporalEvent,
        Self::TimeClockPolicy,
        Self::RecordingDataset,
        Self::Recording,
        Self::RecordingLayer,
        Self::RecordingReadGrant,
        Self::RecordingProjectionReceipt,
        Self::RecordingIngestStream,
        Self::RecordingIngestBatch,
        Self::RecordingBlueprint,
        Self::Agent,
        Self::Wake,
        Self::AgentEpisode,
        Self::AgentTask,
        Self::AgentInputRequest,
        Self::AuditEvent,
        Self::OutboxEvent,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Enterprise => "enterprise",
            Self::Tenant => "tenant",
            Self::Principal => "principal",
            Self::Group => "principal_group",
            Self::OauthClient => "oauth_client",
            Self::McpServer => "mcp_server",
            Self::Profile => "profile",
            Self::PolicyRevision => "policy_revision",
            Self::GatewayControlRevision => "gateway_control_revision",
            Self::GatewayControlObject => "gateway_control_object",
            Self::GatewayControlActive => "gateway_control_active",
            Self::GatewayResourceSubscription => "gateway_resource_subscription",
            Self::GatewayJwtRevocation => "gateway_jwt_revocation",
            Self::GatewayReplayId => "gateway_replay_id",
            Self::GatewayAuthorizationRequest => "gateway_authorization_request",
            Self::GatewayAuthorizationCode => "gateway_authorization_code",
            Self::GatewayRefreshFamily => "gateway_refresh_family",
            Self::GatewayRefreshToken => "gateway_refresh_token",
            Self::Task => "task",
            Self::TaskIdempotency => "task_idempotency",
            Self::TaskInput => "task_input",
            Self::ProviderJob => "provider_job",
            Self::ProviderEvent => "provider_event",
            Self::ArtifactBlob => "artifact_blob",
            Self::ArtifactOccurrence => "artifact_occurrence",
            Self::ArtifactGrant => "artifact_grant",
            Self::ShareLink => "share_link",
            Self::ArtifactWriteCapability => "artifact_write_capability",
            Self::ArtifactWriteRedemption => "artifact_write_redemption",
            Self::ArtifactAccessRequest => "artifact_access_request",
            Self::MediaTaskContext => "media_task_context",
            Self::MediaUsage => "media_usage",
            Self::DomainUsage => "domain_usage",
            Self::Frame => "frame",
            Self::CoordinateOperation => "coordinate_operation",
            Self::MapSource => "map_source",
            Self::MapDatasetRelease => "map_dataset_release",
            Self::MapActiveRelease => "map_active_release",
            Self::MapMobilityProfile => "map_mobility_profile",
            Self::MapRestriction => "map_restriction",
            Self::MapOperationalSnapshot => "map_operational_snapshot",
            Self::MapRoute => "map_route",
            Self::MapRouteDependency => "map_route_dependency",
            Self::MapRouteMatrix => "map_route_matrix",
            Self::MapAcquisition => "map_acquisition",
            Self::TimeSource => "time_source",
            Self::TimeAuthorityRelease => "time_authority_release",
            Self::TimeActiveAuthority => "time_active_authority",
            Self::TimeAcquisition => "time_acquisition",
            Self::TimeCalendarVersion => "time_calendar_version",
            Self::TimeMissionEpoch => "time_mission_epoch",
            Self::TimeTemporalEvent => "time_temporal_event",
            Self::TimeClockPolicy => "time_clock_policy",
            Self::RecordingDataset => "recording_dataset",
            Self::Recording => "recording",
            Self::RecordingLayer => "recording_layer",
            Self::RecordingReadGrant => "recording_read_grant",
            Self::RecordingProjectionReceipt => "recording_projection_receipt",
            Self::RecordingIngestStream => "recording_ingest_stream",
            Self::RecordingIngestBatch => "recording_ingest_batch",
            Self::RecordingBlueprint => "recording_blueprint",
            Self::Agent => "agent",
            Self::Wake => "wake",
            Self::AgentEpisode => "agent_episode",
            Self::AgentTask => "agent_task",
            Self::AgentInputRequest => "agent_input_request",
            Self::AuditEvent => "audit_event",
            Self::OutboxEvent => "outbox_event",
        }
    }
}

impl fmt::Display for PlatformTable {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}
