apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: uav-sim-chart
  namespace: flux-system
spec:
  interval: 5m
  timeout: 2m
  url: oci://charts-registry.flux-system.svc.cluster.local:5000/charts/uav-sim
  insecure: true
  ref:
    digest: sha256:00322a6c8fdb7d460f3b0c336b6d7f4c49fa310940d803de3b2fa01aa7f8cbf5
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
