apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: uav-sim-chart
  namespace: flux-system
spec:
  interval: 5m
  timeout: 2m
  url: oci://charts-registry.flux-system.svc.cluster.local:5000/charts/uav-sim
  insecure: true
  ref:
    digest: sha256:592c0bc6cae84ef2b32359dc64b17dda22266ddff153fd374a15075b11fb4d19
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
