apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: veoveo-chart
  namespace: flux-system
spec:
  interval: 5m
  timeout: 2m
  url: oci://charts-registry.flux-system.svc.cluster.local:5000/charts/veoveo
  insecure: true
  ref:
    digest: sha256:77ee85883845041940cacaea6e0ef455b6f8c9b8fd6b3cfc6a088ce3edeff88a
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
