apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: veoveo-chart
  namespace: flux-system
spec:
  interval: 5m
  timeout: 2m
  url: oci://charts-registry.flux-system.svc.cluster.local:5000/charts/veoveo
  insecure: true
  ref:
    digest: sha256:1032eac91aa17097dae1c0f2929195bf3a1e09a5b6924a4293048da917f3828b
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
