//! Client contract for the shared artifact plane.
//!
//! The artifact service is the single byte-level policy-enforcement point (PEP)
//! for the platform: domain servers (media, timeseries, optimization, duckdb)
//! stop owning private buckets and instead call this service with the
//! gateway-signed identity they already received. The service owns the object
//! store and the grant ledger, and every read/write is decided by
//! [`crate::access::decide`].
//!
//! This module is transport-agnostic: it defines the [`ArtifactPlane`] trait
//! the domain servers program against, the JSON wire DTOs the HTTP service and
//! client exchange, and a typed error. The service binary and the concrete HTTP
//! client live in the `artifact-service` crate.
//!
//! Security invariants encoded here:
//!
//! - **Client never asserts tenant or owner.** [`PutArtifactRequest`] carries
//!   only presentation and client-declared sensitivity. The service stamps
//!   `tenant_id` and `owner_id` from the verified [`GatewayInternalIdentity`],
//!   so a caller cannot write into another tenant or forge ownership.
//! - **Content hashes are internal.** Public identities are opaque occurrence
//!   UUIDs. Implementations may deduplicate blobs by `(tenant, sha256)` without
//!   exposing that hash as an address or cross-tenant existence oracle.
//! - **Async writes are capability-bound.** A domain server obtains a bounded
//!   artifact-write capability while it has a live verified identity. It never
//!   mints a replacement identity when a webhook completes later.

use std::{
    collections::BTreeSet,
    fmt,
    num::{NonZeroU32, NonZeroU64},
};

use chrono::{DateTime, Utc};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::AccessSubject;
use crate::access::{AccessDecision, AccessLevel, ArtifactId, Grant, GroupMembership};
use crate::gateway::{DataLabelId, PrincipalId, TenantId, WorkContextId};
use crate::internal_auth::GatewayInternalIdentity;
use crate::storage::{ArtifactMetadata, ArtifactObject, ArtifactReleaseState};

/// Maximum serialized size of [`PutArtifactRequest`].
///
/// Artifact bytes belong in the data plane. This bound keeps presentation,
/// compliance, and provenance descriptors small enough for the control plane.
pub const MAX_ARTIFACT_PUT_DESCRIPTOR_BYTES: usize = 4 * 1024;

macro_rules! artifact_uuid_id {
    ($name:ident, $label:literal) => {
        #[derive(
            Clone,
            Copy,
            Debug,
            PartialEq,
            Eq,
            PartialOrd,
            Ord,
            Hash,
            Serialize,
            Deserialize,
            JsonSchema,
        )]
        #[serde(try_from = "String", into = "String")]
        pub struct $name(uuid::Uuid);

        impl $name {
            pub fn new() -> Self {
                Self(uuid::Uuid::now_v7())
            }

            pub fn parse(value: impl AsRef<str>) -> Result<Self, ArtifactPlaneError> {
                let value = uuid::Uuid::parse_str(value.as_ref()).map_err(|_| {
                    ArtifactPlaneError::InvalidRequest(concat!($label, " must be a UUIDv7").into())
                })?;
                if value.get_version_num() != 7 {
                    return Err(ArtifactPlaneError::InvalidRequest(
                        concat!($label, " must be a UUIDv7").into(),
                    ));
                }
                Ok(Self(value))
            }

            pub const fn as_uuid(self) -> uuid::Uuid {
                self.0
            }
        }

        impl Default for $name {
            fn default() -> Self {
                Self::new()
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                self.0.fmt(f)
            }
        }

        impl TryFrom<String> for $name {
            type Error = ArtifactPlaneError;

            fn try_from(value: String) -> Result<Self, Self::Error> {
                Self::parse(value)
            }
        }

        impl From<$name> for String {
            fn from(value: $name) -> Self {
                value.to_string()
            }
        }
    };
}

artifact_uuid_id!(ArtifactWriteCapabilityId, "artifact write capability id");

/// Stable caller-selected identity for one asynchronous artifact write.
///
/// Retrying a capability redemption with the same key returns the UUIDv7
/// occurrence reserved by the first successful attempt. Before any occurrence
/// is staged, a retry may rebind that reservation to regenerated bytes; after
/// staging or finalization, retries always return the original occurrence.
#[derive(Debug, Clone, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize, JsonSchema)]
#[serde(transparent)]
pub struct ArtifactWriteIdempotencyKey(String);

impl ArtifactWriteIdempotencyKey {
    pub fn new(value: impl Into<String>) -> Result<Self, ArtifactPlaneError> {
        let value = value.into();
        if value.is_empty()
            || value.len() > 256
            || value.chars().any(char::is_control)
            || value.trim() != value
        {
            return Err(ArtifactPlaneError::InvalidRequest(
                "artifact write idempotency key must be 1..=256 trimmed, non-control characters"
                    .into(),
            ));
        }
        Ok(Self(value))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for ArtifactWriteIdempotencyKey {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl<'de> Deserialize<'de> for ArtifactWriteIdempotencyKey {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        Self::new(String::deserialize(deserializer)?).map_err(serde::de::Error::custom)
    }
}
artifact_uuid_id!(ArtifactShareLinkId, "artifact share link id");
artifact_uuid_id!(ArtifactAccessRequestId, "artifact access request id");

/// Opaque identity of an artifact-write capability issued by the artifact
/// service. This is not an artifact id or a gateway identity assertion.
/// Bearer secret returned once by the artifact service. The issuing artifact
/// service stores only a one-way hash; the authorized domain server retains
/// the secret with the task that needs it after asynchronous completion.
#[derive(Clone, PartialEq, Eq, Serialize, JsonSchema)]
#[serde(transparent)]
pub struct ArtifactWriteCapabilitySecret(String);

impl ArtifactWriteCapabilitySecret {
    pub fn new(value: impl Into<String>) -> Result<Self, ArtifactPlaneError> {
        let value = value.into();
        if value.len() < 32 || value.chars().any(char::is_whitespace) {
            return Err(ArtifactPlaneError::InvalidRequest(
                "artifact write capability secret must be at least 32 non-whitespace characters"
                    .to_string(),
            ));
        }
        Ok(Self(value))
    }

    pub fn expose_secret(&self) -> &str {
        &self.0
    }
}

impl fmt::Debug for ArtifactWriteCapabilitySecret {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("ArtifactWriteCapabilitySecret(<redacted>)")
    }
}

impl<'de> Deserialize<'de> for ArtifactWriteCapabilitySecret {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        Self::new(value).map_err(serde::de::Error::custom)
    }
}

/// Request a capability while a live gateway identity is available. The
/// artifact service binds the caller principal, tenant, labels, profile, and
/// server from that verified identity; clients cannot assert them here.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct IssueArtifactWriteCapabilityRequest {
    pub task_id: String,
    pub expires_at: DateTime<Utc>,
    pub max_artifact_count: NonZeroU32,
    pub max_total_bytes: NonZeroU64,
}

/// One-time issuance response. `secret` is returned only here and is redacted
/// from Debug output.
#[derive(Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct IssuedArtifactWriteCapability {
    pub capability_id: ArtifactWriteCapabilityId,
    pub secret: ArtifactWriteCapabilitySecret,
    pub task_id: String,
    pub expires_at: DateTime<Utc>,
}

impl fmt::Debug for IssuedArtifactWriteCapability {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("IssuedArtifactWriteCapability")
            .field("capability_id", &self.capability_id)
            .field("secret", &"<redacted>")
            .field("task_id", &self.task_id)
            .field("expires_at", &self.expires_at)
            .finish()
    }
}

/// Typed redemption request. The capability bearer secret travels in the
/// Authorization header and is intentionally absent from this serializable
/// request body/header shape.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct RedeemArtifactWriteCapabilityRequest {
    pub capability_id: ArtifactWriteCapabilityId,
    pub task_id: String,
    pub idempotency_key: ArtifactWriteIdempotencyKey,
    pub artifact: PutArtifactRequest,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct SetArtifactReleaseStateRequest {
    pub release_state: ArtifactReleaseState,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct CreateArtifactShareLinkRequest {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_downloads: Option<NonZeroU64>,
}

#[derive(Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct ArtifactShareLink {
    pub link_id: ArtifactShareLinkId,
    pub artifact_id: ArtifactId,
    pub url: String,
    pub expires_at: DateTime<Utc>,
    pub max_downloads: Option<NonZeroU64>,
}

impl fmt::Debug for ArtifactShareLink {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ArtifactShareLink")
            .field("link_id", &self.link_id)
            .field("artifact_id", &self.artifact_id)
            .field("url", &"<redacted>")
            .field("expires_at", &self.expires_at)
            .field("max_downloads", &self.max_downloads)
            .finish()
    }
}

/// What a domain server presents when acting on a principal's behalf.
///
/// The domain server has already verified the incoming gateway token; it
/// forwards the same `bearer_token` to the plane (no re-minting, no shared
/// signing secret in domain servers) and carries the parsed `identity` for
/// local reasoning. `memberships` is the `(GroupId, GroupRole)` set derived from
/// the signed principal and used to resolve group grants.
#[derive(Clone)]
pub struct PlaneCaller {
    pub bearer_token: String,
    pub identity: GatewayInternalIdentity,
    pub memberships: BTreeSet<GroupMembership>,
}

impl fmt::Debug for PlaneCaller {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("PlaneCaller")
            .field("bearer_token", &"<redacted>")
            .field("identity", &self.identity)
            .field("memberships", &self.memberships)
            .finish()
    }
}

impl PlaneCaller {
    /// Labels the caller carries as clearance (from the verified identity).
    pub fn clearance(&self) -> &BTreeSet<DataLabelId> {
        &self.identity.actor.data_labels
    }

    /// Tenant the caller is bound to, if any.
    pub fn tenant(&self) -> Option<&TenantId> {
        self.identity.actor.tenant.as_ref()
    }
}

/// Presentation and client-declared sensitivity for a new artifact.
///
/// Deliberately has no `tenant_id` or `owner_id`: those are stamped by the
/// service from the verified identity and can never be asserted by the client.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct PutArtifactRequest {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    /// Client-declared classification, unioned into the artifact's labels.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub classification: Option<DataLabelId>,
    #[serde(default, skip_serializing_if = "BTreeSet::is_empty")]
    pub data_labels: BTreeSet<DataLabelId>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub retention_expires_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Value::is_null")]
    pub metadata: Value,
}

impl PutArtifactRequest {
    /// The full label set the artifact carries: classification unioned with the
    /// explicit data labels. This is what MAC is evaluated against.
    pub fn effective_labels(&self) -> BTreeSet<DataLabelId> {
        let mut labels = self.data_labels.clone();
        if let Some(class) = &self.classification {
            labels.insert(class.clone());
        }
        labels
    }
}

/// Internal bounded streaming upload descriptor.
///
/// The expected length and digest are mandatory because the service must reject
/// a corrupt or truncated body before committing an object or occurrence.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct StreamArtifactRequest {
    /// Pre-reserved occurrence identity. Recording publication uses the
    /// distinct `RecordingLayerId` wrapper around this same UUIDv7.
    pub artifact_id: ArtifactId,
    pub artifact: PutArtifactRequest,
    pub expected_byte_len: u64,
    pub expected_sha256: String,
}

/// A grant mutation request. The occurrence id travels in the request path.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct PutGrantRequest {
    pub subject: AccessSubject,
    pub level: AccessLevel,
}

/// The grants recorded for one artifact.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct GrantList {
    pub grants: Vec<Grant>,
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, JsonSchema,
)]
#[serde(rename_all = "snake_case")]
pub enum ArtifactAccessRequestState {
    Pending,
    Approved,
    Denied,
    Cancelled,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum ArtifactAccessRequestDecision {
    Approve,
    Deny,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum ArtifactAccessRequestScope {
    Mine,
    Reviewable,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct CreateArtifactAccessRequest {
    pub requested_level: AccessLevel,
    pub justification: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct DecideArtifactAccessRequest {
    pub decision: ArtifactAccessRequestDecision,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct ArtifactAccessRequest {
    pub id: ArtifactAccessRequestId,
    pub artifact_id: ArtifactId,
    pub work_context: WorkContextId,
    pub requester: PrincipalId,
    pub requested_level: AccessLevel,
    pub justification: String,
    pub state: ArtifactAccessRequestState,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub decided_by: Option<PrincipalId>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub decision_note: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub decided_at: Option<DateTime<Utc>>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct ListArtifactAccessRequests {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scope: Option<ArtifactAccessRequestScope>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<ArtifactAccessRequestState>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<ArtifactAccessRequestId>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<u16>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct ArtifactAccessRequestPage {
    pub requests: Vec<ArtifactAccessRequest>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<ArtifactAccessRequestId>,
}

/// Keyset-paginated discovery request for artifacts visible to the caller.
///
/// The cursor is an opaque occurrence identity, not a content hash or storage
/// key. Implementations must still apply the complete artifact policy to every
/// returned item.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct ListArtifactsRequest {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<ArtifactId>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<u16>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct ArtifactPage {
    pub artifacts: Vec<ArtifactMetadata>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<ArtifactId>,
}

/// Typed failure surface for the plane. `Denied` carries the [`AccessDecision`]
/// so audit evidence keeps the reason chain (tenant / clearance / need-to-know).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ArtifactPlaneError {
    /// No such artifact (or the caller may not learn that it exists).
    NotFound,
    /// Access denied, with the deciding reason for audit.
    Denied(AccessDecision),
    /// The caller presented no usable identity.
    Unauthenticated,
    /// The request was malformed (bad id, URI, labels, or limits).
    InvalidRequest(String),
    /// A conflicting state prevented the mutation.
    Conflict(String),
    /// Transport or backend failure.
    Transport(String),
}

impl std::fmt::Display for ArtifactPlaneError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::NotFound => f.write_str("artifact not found"),
            Self::Denied(d) => write!(f, "access denied: {d:?}"),
            Self::Unauthenticated => f.write_str("unauthenticated"),
            Self::InvalidRequest(m) => write!(f, "invalid request: {m}"),
            Self::Conflict(m) => write!(f, "conflict: {m}"),
            Self::Transport(m) => write!(f, "transport error: {m}"),
        }
    }
}

impl std::error::Error for ArtifactPlaneError {}

/// The interface every domain server programs against to reach the plane.
///
/// Uses native `async fn` in traits (edition 2024). Callers are generic over
/// the concrete plane implementation, so no dynamic dispatch or `async-trait`
/// dependency is needed; tests substitute an in-memory reference PEP.
pub trait ArtifactPlane {
    /// Store `bytes`, stamping tenant/owner from the caller's identity and
    /// recording an owner `Admin` grant. Returns the canonical metadata.
    fn put(
        &self,
        caller: &PlaneCaller,
        request: PutArtifactRequest,
        bytes: Vec<u8>,
    ) -> impl std::future::Future<Output = Result<ArtifactMetadata, ArtifactPlaneError>> + Send;

    /// Fetch bytes + metadata if the caller has at least `level`.
    fn get(
        &self,
        caller: &PlaneCaller,
        artifact_id: &ArtifactId,
        level: AccessLevel,
    ) -> impl std::future::Future<Output = Result<ArtifactObject, ArtifactPlaneError>> + Send;

    /// Metadata only, gated at `Read`.
    fn head(
        &self,
        caller: &PlaneCaller,
        artifact_id: &ArtifactId,
    ) -> impl std::future::Future<Output = Result<ArtifactMetadata, ArtifactPlaneError>> + Send;

    /// Discover metadata for artifacts on which the caller has at least read
    /// access. Results are ordered newest first and keyset-paginated.
    fn list(
        &self,
        caller: &PlaneCaller,
        request: ListArtifactsRequest,
    ) -> impl std::future::Future<Output = Result<ArtifactPage, ArtifactPlaneError>> + Send;

    /// Resolve a neutral `artifact://{id}` plane URI to bytes, gated at `Read`.
    /// This is how a server feeds another server's artifact into its own tool.
    fn resolve(
        &self,
        caller: &PlaneCaller,
        uri: &str,
    ) -> impl std::future::Future<Output = Result<ArtifactObject, ArtifactPlaneError>> + Send;

    /// Add or raise a grant. Requires the caller to hold `Admin` on the artifact.
    fn grant(
        &self,
        caller: &PlaneCaller,
        artifact_id: &ArtifactId,
        subject: AccessSubject,
        level: AccessLevel,
    ) -> impl std::future::Future<Output = Result<(), ArtifactPlaneError>> + Send;

    /// Remove a grant. Requires the caller to hold `Admin` on the artifact.
    fn revoke(
        &self,
        caller: &PlaneCaller,
        artifact_id: &ArtifactId,
        subject: &AccessSubject,
    ) -> impl std::future::Future<Output = Result<(), ArtifactPlaneError>> + Send;

    /// List an artifact's grants. Requires `Admin` on the artifact.
    fn list_grants(
        &self,
        caller: &PlaneCaller,
        artifact_id: &ArtifactId,
    ) -> impl std::future::Future<Output = Result<Vec<Grant>, ArtifactPlaneError>> + Send;

    /// Change whether an artifact may be published. Requires `Admin`.
    fn set_release_state(
        &self,
        caller: &PlaneCaller,
        artifact_id: &ArtifactId,
        release_state: ArtifactReleaseState,
    ) -> impl std::future::Future<Output = Result<ArtifactMetadata, ArtifactPlaneError>> + Send;

    /// Create a read-only anyone-with-link bearer. Requires `Admin` and an
    /// explicitly releasable artifact.
    fn create_share_link(
        &self,
        caller: &PlaneCaller,
        artifact_id: &ArtifactId,
        request: CreateArtifactShareLinkRequest,
    ) -> impl std::future::Future<Output = Result<ArtifactShareLink, ArtifactPlaneError>> + Send;

    /// Revoke a public share link. Requires `Admin` on its artifact.
    fn revoke_share_link(
        &self,
        caller: &PlaneCaller,
        artifact_id: &ArtifactId,
        link_id: &ArtifactShareLinkId,
    ) -> impl std::future::Future<Output = Result<(), ArtifactPlaneError>> + Send;

    fn create_access_request(
        &self,
        caller: &PlaneCaller,
        artifact_id: &ArtifactId,
        request: CreateArtifactAccessRequest,
    ) -> impl std::future::Future<Output = Result<ArtifactAccessRequest, ArtifactPlaneError>> + Send;

    fn list_access_requests(
        &self,
        caller: &PlaneCaller,
        request: ListArtifactAccessRequests,
    ) -> impl std::future::Future<Output = Result<ArtifactAccessRequestPage, ArtifactPlaneError>> + Send;

    fn decide_access_request(
        &self,
        caller: &PlaneCaller,
        request_id: &ArtifactAccessRequestId,
        decision: DecideArtifactAccessRequest,
    ) -> impl std::future::Future<Output = Result<ArtifactAccessRequest, ArtifactPlaneError>> + Send;

    fn cancel_access_request(
        &self,
        caller: &PlaneCaller,
        request_id: &ArtifactAccessRequestId,
    ) -> impl std::future::Future<Output = Result<ArtifactAccessRequest, ArtifactPlaneError>> + Send;
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use chrono::{TimeDelta, Utc};
    use serde_json::json;

    use super::*;
    use crate::gateway::DataLabelId;

    #[test]
    fn occurrence_and_control_ids_are_uuid_v7() {
        let artifact = ArtifactId::new();
        let capability = ArtifactWriteCapabilityId::new();
        let link = ArtifactShareLinkId::new();
        let access_request = ArtifactAccessRequestId::new();

        assert_eq!(artifact.as_uuid().get_version_num(), 7);
        assert_eq!(capability.as_uuid().get_version_num(), 7);
        assert_eq!(link.as_uuid().get_version_num(), 7);
        assert_eq!(access_request.as_uuid().get_version_num(), 7);
        assert_eq!(ArtifactId::parse(artifact.to_string()).unwrap(), artifact);
        assert_eq!(
            ArtifactAccessRequestId::parse(access_request.to_string()).unwrap(),
            access_request
        );
        assert!(ArtifactId::parse(uuid::Uuid::new_v4().to_string()).is_err());
        assert!(ArtifactWriteCapabilityId::parse("not-a-uuid").is_err());
    }

    #[test]
    fn artifact_write_idempotency_key_is_validated() {
        let key = ArtifactWriteIdempotencyKey::new("media:task:output:0").unwrap();
        assert_eq!(key.as_str(), "media:task:output:0");
        assert!(ArtifactWriteIdempotencyKey::new("").is_err());
        assert!(ArtifactWriteIdempotencyKey::new(" leading").is_err());
        assert!(ArtifactWriteIdempotencyKey::new("line\nbreak").is_err());
        assert!(ArtifactWriteIdempotencyKey::new("x".repeat(257)).is_err());
    }

    #[test]
    fn effective_labels_union_classification() {
        let classification = DataLabelId::new("cui").unwrap();
        let explicit = DataLabelId::new("us_only").unwrap();
        let request = PutArtifactRequest {
            classification: Some(classification.clone()),
            data_labels: BTreeSet::from([explicit.clone()]),
            metadata: json!({"producer": "test"}),
            ..Default::default()
        };
        assert_eq!(
            request.effective_labels(),
            BTreeSet::from([classification, explicit])
        );
    }

    #[test]
    fn capability_secret_is_validated_and_redacted() {
        assert!(ArtifactWriteCapabilitySecret::new("short").is_err());
        let secret = ArtifactWriteCapabilitySecret::new("s".repeat(32)).unwrap();
        assert_eq!(
            format!("{secret:?}"),
            "ArtifactWriteCapabilitySecret(<redacted>)"
        );
        let issued = IssuedArtifactWriteCapability {
            capability_id: ArtifactWriteCapabilityId::new(),
            secret,
            task_id: "task-1".into(),
            expires_at: Utc::now() + TimeDelta::minutes(5),
        };
        assert!(!format!("{issued:?}").contains(&"s".repeat(32)));
    }

    #[test]
    fn share_link_defaults_do_not_assert_limits() {
        let request = CreateArtifactShareLinkRequest::default();
        assert!(request.expires_at.is_none());
        assert!(request.max_downloads.is_none());
        let value = serde_json::to_value(request).unwrap();
        assert_eq!(value, json!({}));
    }

    #[test]
    fn share_link_debug_redacts_the_bearer_url() {
        let token = "public-share-token-that-must-not-be-logged";
        let link = ArtifactShareLink {
            link_id: ArtifactShareLinkId::new(),
            artifact_id: ArtifactId::new(),
            url: format!("https://veoveo.example/s/{token}"),
            expires_at: Utc::now() + TimeDelta::minutes(5),
            max_downloads: None,
        };
        let diagnostic = format!("{link:?}");
        assert!(!diagnostic.contains(token));
        assert!(diagnostic.contains("<redacted>"));
    }
}
