apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitops/namespace.yaml
  - gitops/sources
  - gitops/releases
  - gitops/cloudflared.yaml
configMapGenerator:
  - name: bioma-gateway-control-plane
    namespace: veoveo
    files:
      - gateway.json
      - recording-producer-jwks.json
      - service-client-jwks.json
      - uav-pilot-jwks.json
  - name: uav-sim-world-binding
    namespace: veoveo
    files:
      - world.json=uav-sim-world.json
  - name: bioma-veoveo-values
    namespace: flux-system
    files:
      - values.yaml=values.yaml
      - k3d-values.yaml=k3d-values.yaml
      - images.lock.yaml=images.lock.yaml
  - name: bioma-uav-sim-values
    namespace: flux-system
    files:
      - uav-sim-values.yaml=uav-sim-values.yaml
      - images.lock.yaml=images.lock.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    reconcile.fluxcd.io/watch: Enabled
  labels:
    app.kubernetes.io/part-of: veoveo
    app.kubernetes.io/managed-by: flux
